program_languages = ['bash','r','python','java','c++','ruby','perl','matlab','javascript','scala','php']
analysis_software = ['excel','tableau','sas','spss','d3','saas','pandas','numpy','scipy','sps','spotfire','scikit','splunk','power','h2o']
ml_framework = ['pytorch','tensorflow','caffe','caffe2','cntk','mxnet','paddle','keras','bigdl']
bigdata_tool = ['hadoop','mapreduce','spark','pig','hive','shark','oozie','zookeeper','flume','mahout','etl']
ml_platform = ['aws','azure','google','ibm']
methodology = ['agile','devops','scrum']
databases = ['sql','nosql','hbase','cassandra','mongodb','mysql','mssql','postgresql','oracle','rdbms','bigquery']
overall_skills_dict = program_languages + analysis_software + ml_framework + bigdata_tool + databases + ml_platform + methodology
education = ['master','phd','undergraduate','bachelor','mba']
overall_dict = overall_skills_dict + education
max_results_per_city = 500
page_record_limit = 50
num_pages = int(max_results_per_city/page_record_limit)
job_link_metadata_file = r'./data/indeed_jobs_links.json'
job_info_file = r'./data/indeed_jobs_info.json'
save_recommendations = r'./data/job_recommendations'
chrome_driver_location = r'./chromedriver'
indian_locations_to_search = ['Bengaluru', 'Delhi']
keyword_to_search_for_scrape = '"data scientist"+OR+"data engineer"+OR+"data analyst"'
old_post_limit_days = 5
resume_location = r'./data/vivek_resume.pdf'
count_of_recommendations = 10